# Generated by Django 4.2.5 on 2023-11-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('headline', models.CharField(max_length=255)),
                ('news_id', models.IntegerField(unique=True)),
                ('image', models.URLField()),
                ('related', models.TextField(blank=True)),
                ('source', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
