name: CI for Group Projects

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  react-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Node for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
        working-directory: ./frontend
      - run: npm run build --if-present
        working-directory: ./frontend
      - run: npm test
        working-directory: ./frontend

  django-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
        working-directory: ./backend
      - run: python manage.py test
        working-directory: ./backend

  run-compose:
    needs: [react-tests, django-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start containers
        run: ./run-compose-dev-ci.sh
      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.dev.yml down
